### PR TITLE
Fixes Issue #6: Adds horizontal option for counters

### LINKED ISSUE #6: Allow horizontal counters
The counters could be horizontal (i.e. arrows pointing left and right) which would save vertical space allowing for more features to be shown at once.

I think this only makes sense for the demand counters so should be chosen using a flag.

### PR DESCRIPTION
**Pull request by dan-snw**
Fixes #6.

## Changes

Added via a flag that defaults to false - I already set it to true for the demand buttons but the unit price ones remain vertical.

This saves space in the case of the demand icons - there still needs to be formatting changes e.g. the fact that the buttons demand buttons aren't quite aligned due to differently sized svgs but that's for a different commit.

### Before:

before

### After:

after

### CODE REVIEW

File: src/Components/DemandArea.tsx [hunk 1]
```diff
@@ -104,6 +106,7 @@ const DemandArea: React.FC<DemandAreaProps> = () => {
           label={demand.pizza.toString()}
           onIncrement={handleAddPizza}
           onDecrement={handleRemovePizza}
+          horizontal={true}
```
Comment (egnwd) [inline src/Components/DemandArea.tsx]: This is equivalent to just passing `horizontal`

File: src/Components/NumberButton.tsx [hunk 2]
```diff
@@ -4,20 +4,31 @@ type NumberButtonProps = {
...
   }) => {
-    return (
+    const verticalCounter = (
       <div className='numberCruncher'>
         <button onClick={onIncrement}>▲</button>
         <span>{label}</span>
         <button onClick={onDecrement}>▼</button>
       </div>
     );
+    const horizontalCounter = (
```
Comment (egnwd) [inline src/Components/NumberButton.tsx]: Here you are setting both consts regardless of the Boolean, it might be neater to pull these out into private components in this file then just render the correct one based on the flag

**Review by egnwd — CHANGES_REQUESTED** [review]

File: src/Components/DemandArea.tsx (hunk 1 above)
Comment (dan-snw) [reply src/Components/DemandArea.tsx]: Good point, I've changed it accordingly.

File: src/Components/NumberButton.tsx (hunk 2 above)
Comment (dan-snw) [reply src/Components/NumberButton.tsx]: Good point, this is now resolved.

**Review by egnwd — APPROVED** [review]
